# Generated by Django 4.1.7 on 2023-03-13 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0002_alter_author_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Выберите автора книги', on_delete=django.db.models.deletion.CASCADE, to='biblios.author', verbose_name='Автор'),
        ),
    ]
